server:
  port: 5280
spring:
  application:
    name: stadium-admin
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/stadium?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui/
      - /swagger-resources/**
      - /**/v2/api-docs
      - /**/*.html
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.map
      - /favicon.ico
      - /admin/login
      - /admin/register
      - /admin/info
      - /admin/logout
      - /minio/upload

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: stadium-admin-secret #JWT加解密使用的密钥
  expiration: 7200 # 604800 #JWT的超期限时间(60*60*2秒)
  tokenHead: 'Bearer ' #JWT负载中拿到的开头

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml

aliyun:
  oss:
    endpoint: oss-cn-hangzhou.aliyuncs.com # oss对外服务的访问域名
    accessKeyId: xxx # 访问身份验证中用到用户标识
    accessKeySecret: xxx # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: clsnull-stadium-oss # oss的存储空间
    policy:
      expire: 300 # 签名有效期(S)
    maxSize: 10 # 上传文件大小(M)
    callback: http://39.98.190.128:8080/aliyun/oss/callback # 文件上传成功后的回调地址
    dir:
      prefix: stadium/images/ # 上传文件夹路径前缀